// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Covid19TestService_Library.Models
{
    public partial class AccessLog
    {
        public int Id { get; set; }
        public DateOnly? EntryDate { get; set; }
    }
}