// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Covid19TestService_Library.Models
{
    public partial class Antigen
    {
        public int Aid { get; set; }
        public int? Lines { get; set; }
        public DateOnly? Takenon { get; set; }
        public bool? Ispositive { get; set; }
        public int? Pid { get; set; }

        public virtual Profile PidNavigation { get; set; }
    }
}