// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Covid19TestService_Library.Models
{
    public partial class Pcr
    {
        public int Pcrid { get; set; }
        public int? Ct { get; set; }
        public DateOnly? Takenon { get; set; }
        public bool? Ispositive { get; set; }
        public int? Pid { get; set; }

        public Pcr(int pcrid, int? ct, DateOnly? takenon, bool? ispositive, int? pid)
        {
            Pcrid = pcrid;
            Ct = ct;
            Takenon = takenon;
            Ispositive = ispositive;
            Pid = pid;
        }

        public virtual Profile PidNavigation { get; set; }
    }
}