// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Covid19TestService_Library.Models
{
    public partial class Profile
    {
        public Profile()
        {
            Antigen = new HashSet<Antigen>();
            Pcr = new HashSet<Pcr>();
        }

        public Profile(int pid, int? uid, string firstname, string lastname, int? phonenumber, int? ssn, DateTime? dob, string address, string city, string country)
        {
            Pid = pid;
            Uid = uid;
            Firstname = firstname;
            Lastname = lastname;
            Phonenumber = phonenumber;
            Ssn = ssn;
            Dob = dob;
            Address = address;
            City = city;
            Country = country;
        }

        public int Pid { get; set; }
        public int? Uid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int? Phonenumber { get; set; }
        public int? Ssn { get; set; }
        public DateTime? Dob { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }

        [JsonIgnore]
        public virtual Users UidNavigation { get; set; }
        public virtual ICollection<Antigen> Antigen { get; set; }
        public virtual ICollection<Pcr> Pcr { get; set; }

        public override string ToString()
        {
            return $"{Firstname} {Lastname}";
        }
    }
}