// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Covid19TestService_Library.Models
{
    public partial class Profile
    {
        public Profile()
        {
            Antigen = new HashSet<Antigen>();
            Pcr = new HashSet<Pcr>();
        }

        public int Pid { get; set; }
        public int? Uid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int? Phonenumber { get; set; }
        public int? Ssn { get; set; }
        public DateOnly? Dob { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }

        public virtual Users UidNavigation { get; set; }
        public virtual ICollection<Antigen> Antigen { get; set; }
        public virtual ICollection<Pcr> Pcr { get; set; }
    }
}