// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Covid19TestService_Library.Models
{
    public partial class Users
    {
        public Users()
        {
            Profile = new HashSet<Profile>();
        }

        public int Uid { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Profile> Profile { get; set; }
    }
}